# Generated by Django 4.2.1 on 2023-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_code_is_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='User_1',
        ),
    ]
